export { Prisma, PrismaClient } from '@prisma/client'
export * from './lib/prisma-client.module'
export * from './lib/prisma.service'
export * from './lib/validators/exist-constraint.validator'
export * from './lib/validators/unique-constraint.validator'
